[programs.localnet]
hto_treasury = "9eF85bwDGA5CgaXgU1jCw13RZsUGY3JJ2x1MM19tJjVh"

[programs.devnet]
hto_treasury = "AHMVst4jghKqSSMDNUWrLjfHQgwD8dod3vFL4KgkJvKZ"

[programs.testnet]
hto_treasury = "3cjoBZpiEe49TiFcyvPVBTmR5GxiYzpGmw2HyJyszphw"

[programs.mainnet]
hto_treasury = "GfXYYi5TFPG5ixdfiXLQacgjZbatqpb9uZZPMTBxMVCx"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./test-keypair.json"

[scripts]
test = "mocha -t 1000000 ./treasuring_scripts/create_state.js"